<?php
$pergunta1 = "<b>Medicamentos de uso contínuo, vacinas, drogas, cigarro ou álcool ingeridos pela mãe antes da gravidez:</b>";
$pergunta2 = "<b>Medicamentos de uso contínuo, vacinas ou drogas, cigarro ou álcool ingeridos pelo pai antes da gravidez</b>";
$pergunta3 = "<b>Medicamentos ingeridos, vacinas, drogas, cigarro ou álcool ingeridos pela mãe durante a gravidez:</b>";
$pergunta4 = "<b>Como foi a gravidez? fatos relevantes?:</b>";
$pergunta5 = "<b>Parto normal ou cesariana? Alguma complicação?:</b>";
$pergunta6 = "<b>Tempo de amamentação:</b>";
$pergunta7 = "<b>Medicamentos ingeridos pela criança até hoje (antibióticos, corticóides, spray nasal, medicamentos para nebulização, antidepressivos, calmantes e outros):</b>";
$pergunta8 = "<b>Cirurgias?:</b>";
$pergunta9 = "<b>Alimentação:</b>";
$pergunta10 = "<b>Dieta restritiva:</b>";
$pergunta11 = "<b>Panelas são de alumínio?:</b>";
$pergunta12 = "<b>Aquecimento do leite foi ou é feito na mamadeira no micro-ondas?:</b>";
$pergunta13 = "<b>Aquecimento de alimentos em potes plásticos no micro-ondas?:</b>";
$pergunta14 = "<b>Urina, fezes normais?:</b>";
$pergunta15 = "<b>Sono:</b>";
$pergunta16 = "<b>Piso de vinil no quarto?:</b>";
$pergunta17 = "<b>Desmaio, convulsão ou epilepsia? início,  frequência,  duração:</b>";
$pergunta18 = "<b>Algum gatilho que marca o início da doença? alguma vacina em particular?</b>";
$pergunta19 = "<b>Idade do diagnóstico:</b>";
$pergunta20 = "<b>Tratamento atual/medicamentos em uso:</b>";
$pergunta21 = "<b>Problemas de saúde:</b>";
$pergunta22 = "<b>Dificuldades  de caminhar, coordenação motora, etc:</b>";
$pergunta23 = "<b>Descrição da personalidade:</b>";
$pergunta24 = "<b>Modo de brincar:</b>";
$pergunta25 = "<b>Comportamento e socialização:</b>";
$pergunta26 = "<b>Fala:</b>";
$pergunta27 = "<b>Frequenta escola? como é o aprendizado?:</b>";
$pergunta28 = "<b>Irmãos:</b>";
$pergunta29 = "<b>Exame de metais pesados? intoxicação de quais?</b>";
$pergunta30 = "<b>Terapia cease anterior? quais detox já feitos e suas reações?:</b>";
$pergunta31 = "<b>Outras  observações:</b>";
/*$pergunta32 = 
$pergunta33 = 
$pergunta34 = 
$pergunta35 =
$pergunta36 = 
$pergunta37 = 
$pergunta38 =
$pergunta39 = 
$pergunta40 = 
$pergunta41 = 
$pergunta42 =*/
?>